### ISSUE TITLE
use chi middleware.LogFormatter in Handler instead of zerolog logger

### ISSUE THREAD

**Issue by jellis18** [go-chi/httplog#18]
currently the private `requestLogger` is hardcoded in the `Handler`. As far as I can tell this means that you cannot customize the logger request fields.

Would it be useful to have the same interface as the chi middleware logger and have the `Handler` take in a `LogFormatter`. That way a user could customize the request fields.

I'm pretty new to this package so I could be wrong but I'd be happy to make an MR with this change.

**Comment by Shubhaankar-Sharma** [comment]
true afaik its not possible to customise logger request fields, but imo if we use something similar to what slog did that would be better...  https://pkg.go.dev/golang.org/x/exp/slog#HandlerOptions, since in my latest pr we're switching to slog, all request fields would be of the type Slog.Attr, we can call a function that we take in the config and supply it with each attribute and they can change the attribute key or customise the value...

**Comment by jellis18** [comment]
@Shubhaankar-Sharma a function would work as well to let a user customize the log fields/attrs, I was just wondering if it would be better to keep the interface from the chi-logger middleware.

**Comment by pkieltyka** [comment]
so, indeed we are phasing our zerolog altogether in favour of "slog"

**Comment by pkieltyka** [comment]
v2 is out, which includes solution
